const CAPITULOS = [50,40,27,36,34,24,21,4,31,24,22,25,29,36,10,13,10,42,150,31,12,8,66,52,5,48,12,14,3,9,1,4,7,3,3,3,2,14,4,28,16,24,21,28,16,16,13,6,6,4,4,5,3,6,4,3,1,13,5,5,3,5,1,1,1,22];

const DEFINICION = [
  ['Génesis', 'gn gen ge'],
  ['Éxodo', 'ex exo exod'],
  ['Levítico', 'lv lev le'],
  ['Números', 'nm num nu'],
  ['Deuteronomio', 'dt deut deu'],
  ['Josué', 'jos jsu'],
  ['Jueces', 'jue jc jz'],
  ['Rut', 'rt rut'],
  ['1 Samuel', '1sa 1sam 1s'],
  ['2 Samuel', '2sa 2sam 2s'],
  ['1 Reyes', '1re 1r 1rey'],
  ['2 Reyes', '2re 2r 2rey'],
  ['1 Crónicas', '1cr 1cro 1cron'],
  ['2 Crónicas', '2cr 2cro 2cron'],
  ['Esdras', 'esd esdr'],
  ['Nehemías', 'neh ne'],
  ['Ester', 'est es'],
  ['Job', 'job jb'],
  ['Salmos', 'sal salmo sl ps'],
  ['Proverbios', 'pr prov pro'],
  ['Eclesiastés', 'ec ecl'],
  ['Cantares', 'cnt cant can cantar cantardeloscantares'],
  ['Isaías', 'is isa'],
  ['Jeremías', 'jer je'],
  ['Lamentaciones', 'lm lam'],
  ['Ezequiel', 'ez eze ezeq'],
  ['Daniel', 'dn dan da'],
  ['Oseas', 'os ose'],
  ['Joel', 'jl joe'],
  ['Amós', 'am amo'],
  ['Abdías', 'abd ab'],
  ['Jonás', 'jon'],
  ['Miqueas', 'miq mi'],
  ['Nahúm', 'nah na'],
  ['Habacuc', 'hab hb'],
  ['Sofonías', 'sof sofo'],
  ['Hageo', 'hag hg'],
  ['Zacarías', 'zac zc'],
  ['Malaquías', 'mal ml'],
  ['Mateo', 'mt mat'],
  ['Marcos', 'mr mc mar mrc'],
  ['Lucas', 'lc luc'],
  ['Juan', 'jn jua'],
  ['Hechos', 'hch hec'],
  ['Romanos', 'ro rom rm'],
  ['1 Corintios', '1co 1cor'],
  ['2 Corintios', '2co 2cor'],
  ['Gálatas', 'gal ga'],
  ['Efesios', 'ef efe'],
  ['Filipenses', 'fil flp filip'],
  ['Colosenses', 'col'],
  ['1 Tesalonicenses', '1ts 1tes'],
  ['2 Tesalonicenses', '2ts 2tes'],
  ['1 Timoteo', '1ti 1tim'],
  ['2 Timoteo', '2ti 2tim'],
  ['Tito', 'tit tt'],
  ['Filemón', 'flm filem'],
  ['Hebreos', 'heb'],
  ['Santiago', 'stg sant snt'],
  ['1 Pedro', '1p 1pe 1ped'],
  ['2 Pedro', '2p 2pe 2ped'],
  ['1 Juan', '1jn 1jua'],
  ['2 Juan', '2jn 2jua'],
  ['3 Juan', '3jn 3jua'],
  ['Judas', 'jud jd'],
  ['Apocalipsis', 'ap apoc apo'],
];

const quitarAcentos = (s) => String(s).normalize('NFD').replace(/[̀-ͯ]/g, '');
const normalizar = (s) => quitarAcentos(s).toLowerCase();
const compacto = (s) => normalizar(s).replace(/[^a-z0-9]/g, '');

const LIBROS = DEFINICION.map(([nombre, alias], i) => ({
  id: i + 1,
  nombre,
  capitulos: CAPITULOS[i],
  testamento: i < 39 ? 'AT' : 'NT',
  alias: alias.split(' '),
  clave: compacto(nombre),
}));

module.exports = { LIBROS, normalizar, compacto, quitarAcentos };
